### ISSUE TITLE
Add GitHub Action to detect unlocalized labels in PRs

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/panorama#48]
Detect any Labels that don't have `text="#` or `text="{` (for data strings) and alert PR author + reviewers about it.

Should also detect `<labelVariable>.text =` as well in JS.

**Comment by tsa96** [comment]
Could also do something like
```bash
for script in **/*.js; do
	if [ "$(head -n 1 "$script")" != 'use strict;' ]; then
		echo "$script" 'not in strict mode'
		exit 1
	fi
done
exit 0
```
though maybe we wanna just add linting at that point

**Comment by Gocnak** [comment]
Use strict can be done by ESLint.

This should also detect setting `(label).text = ` in JavaScript files

**Comment by tsa96** [comment]
There's some numeric strings we do that this isn't appropriate for. To me, spotting this stuff is what code review is for. Doing a regex in CI that detects this sounds hard to get right, and more effort than it's worth. I think we should close this issue.

**Comment by Gocnak** [comment]
Yeah alright. I'll close this and disable issues for this repo finally.
